name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install the library
        run: |
          pip install .

      - name: Run tests
        run: |
          python -m unittest discover -s tests

  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 ./APOLLO_LIBRARY --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 ./APOLLO_LIBRARY --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

          
  doc_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check documentation coverage with pydocstyle
        run: |
          pip install pydocstyle
          pydocstyle .
