name: CI

on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 ./crepe --count --select=E9,F63,F7,F82 --show-source --statistics
#          flake8 ./crepe --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

          
  doc_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check documentation coverage with pydocstyle
        run: |
          pip install pydocstyle
          pydocstyle .
